resources:
  repositories:
    - repository: templates
      type: "git"
      name: "Digital Insights Dashboard/build-templates"
      ref: refs/heads/master

trigger:
  branches:
    include:
    - "*"
  tags:
    include:
    - "*"

variables:
  - group: digital-insight
  - name: registryName
    value: digitalinsight
  - name: module
    value: digitalops
  - name: component
    value: ui
  - name: projectName
    value: '$(module)-$(component)'
  - name: imageName
    value: '$(projectName)'
  - name: registryServerName
    value: '$(registryName).azurecr.io'

jobs:
- template: react.yml@templates
  parameters:
    module: '$(module)'
    component: '$(component)'
    projectName: '$(projectName)'
    imageName: '$(imageName)'
    registryLogin: '$(registryLogin)'
    registryPassword: '$(registryPassword)'
    tenantId: '$(tenantId)'
    registryName: '$(registryName)'
    registryServerName: '$(registryServerName)'
