trigger:
  branches:
    include:
    - "*"

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.10.0'
    architecture: 'x64'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
      command: install    

- script: |
    npm run build
  displayName: 'npm build'