resources:
  repositories:
    - repository: templates
      type: "git"
      name: "Digital Insights Dashboard/build-templates"
      ref: refs/heads/master

trigger:
  branches:
    include:
    - "*"
  tags:
    include:
    - "*"

variables:
  - group: digital-insight
  - name: registryName
    value: digitalinsight
  - name: module
    value: digitalops
  - name: component
    value: ui
  - name: projectName
    value: '$(module)-$(component)'
  - name: imageName
    value: '$(projectName)'
  - name: registryServerName
    value: '$(registryName).azurecr.io'

jobs:
- job: 'angular cli'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.10.0'
      architecture: 'x64'
    displayName: 'Install Node.js'

  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
        command: install    

  - script: |
      npm run build
    displayName: 'npm build'
  
  - template: templates/docker-build.yml
    parameters:
      registryServerName: '${{ parameters.registryServerName }}'
      imageName: '${{ parameters.imageName }}'
      subPath: ${{ parameters.subPath }}

  - template: templates/docker-push.yml
    parameters:
      registryLogin: '${{ parameters.registryLogin }}'
      registryPassword: '${{ parameters.registryPassword }}'
      tenantId: '${{ parameters.tenantId }}'
      registryName: '${{ parameters.registryName }}'
      imageName: '${{ parameters.imageName }}'
      registryServerName: '${{ parameters.registryServerName }}'
      subPath: ${{ parameters.subPath }}