export const SET_EXEC_DATA = "SET_EXEC_DATA";
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const LOAD_CURRENT_SPRINT = "LOAD_CURRENT_SPRINT";
export const SET_CHARTS_DETAILS = "SET_CHARTS_DETAILS";
export const SET_CURRENT_TAB = "SET_CURRENT_TAB";
export const SET_CHART_TYPE = "SET_CHART_TYPE";