export const labelConst = [{
	clientName: 'digitalops',
	clientId: 'DOPS',
	mappings: {
			bgColor: true,
			logoName: 'DevOps Dashboard',
			projectLabel: 'Projects',
			teamLabel: 'Teams',
			sprintLabel: 'Sprints',
			count: [{name:'Head Count'},{name:'Sprint Count'},{name: 'Team Head Count'}],
			feature: 'Features',
			userStory: 'User Stories',
			repository: 'Repository',
			branch: 'Branch',
			release: 'Release',
			roleDesignation: true,
			overviewBtn: 'Overview',
			buildBtn: 'Build',
			codeBtn: 'Code',
			alertBtn: 'Alerts',
			policiesBtn: 'Policies',
			critical: 'Critical',
			high: 'High',
			medium:'Medium',
			low: 'Low',
			veryLow: 'Very Low',
			major: 'Major',
			minor: 'Minor',
			tabItems: [{name:'Overview',eventKey:'overview'},
						{name:'Security',eventKey:'security'},
						{name: 'Velocity and Efficiency',eventKey:'velocity'},
						{name: 'Quality',eventKey:'quality'},
						{name: 'Insights',eventKey:'insights'}],
	}
},
{
	clientName: 'aia',
	clientId: 'AIA',
	mappings: {
			bgColor: false,
			logoName: 'AIA Dashboard',
			projectLabel: 'Projects',
			teamLabel: 'Teams',
			sprintLabel: 'Sprints',
			count: [{name:'Project Members'},{name:'Sprints'},{name: 'Team Members'}],
			feature: 'Features',
			userStory: 'User Stories',
			repository: 'Repository',
			branch: 'Branch',
			release: 'Release',
			roleDesignation: true,
			overviewBtn: 'Overview',
			buildBtn: 'Build',
			codeBtn: 'Code',
			alertBtn: 'Alerts',
			policiesBtn: 'Policies',
			critical: 'Critical',
			high: 'High',
			medium:'Medium',
			low: 'Low',
			veryLow: 'Very Low',
			major: 'Major',
			minor: 'Minor',
			tabItems: [{name:'Overview',eventKey:'overview'},
						{name:'Security',eventKey:'security'},
						{name: 'Velocity and Efficiency',eventKey:'velocity'},
						{name: 'Quality',eventKey:'quality'},
						{name: 'Insights',eventKey:'insights'}]

	}
},
{
	clientName: 'wpc',
	clientId: 'WPC',
	mappings: {
			bgColor: true,
			logoName: 'EY Dash',
			projectLabel: 'Portfolio',
			teamLabel: 'Projects',
			sprintLabel: 'Sprints',
			count: [],
			feature: 'Features',
			userStory: 'User Stories',
			repository: 'Repository',
			branch: 'Branch',
			release: 'Release',
			roleDesignation: false,
			overviewBtn: 'Overview',
			buildBtn: 'Build',
			codeBtn: 'Code',
			alertBtn: 'Alerts',
			policiesBtn: 'Policies',
			critical: 'Critical',
			high: 'High',
			medium:'Medium',
			low: 'Low',
			veryLow: 'Very Low',
			major: 'Major',
			minor: 'Minor',
			tabItems: [{name: 'Velocity and Efficiency',eventKey:'velocity'},
						{name: 'Quality',eventKey:'quality'},
						{name:'Security',eventKey:'security'},
						{name: 'Insights',eventKey:'insights'}]
	}
}];