export const labelConst = [{
	clientName: 'digitalops',
	clientId: 'DOPS',
	mappings: {
			showSprintDrop: false,
			navLogoUrl: 'overview',
			bgColor: 'dark',
			logoName: 'DevOps Dashboard',
			projectLabel: 'Project',
			teamLabel: 'Teams',
			sprintLabel: 'Sprints',
			count: [{name:'Head Count'},{name:'Sprint Count'},{name: 'Team Head Count'}],
			feature: 'Features',
			userStory: 'User Stories',
			repository: 'Repository',
			branch: 'Branch',
			release: 'Release',
			roleDesignation: true,
			overviewBtn: 'Overview',
			buildBtn: 'Build',
			codeBtn: 'Code',
			alertBtn: 'Alerts',
			policiesBtn: 'Policies',
			critical: 'Critical',
			high: 'High',
			medium:'Medium',
			low: 'Low',
			veryLow: 'Very Low',
			major: 'Major',
			minor: 'Minor',
			tabItems: [{id:"1",name:'Overview',eventKey:'overview'},
						{id:"2",name: 'Velocity and Efficiency',eventKey:'velocity'},
						{id:"3",name: 'Quality',eventKey:'quality'},
						{id:"4",name:'Security',eventKey:'security',toolsDetails:
																[{name:'SCA',label:'WhiteSource'},
																{name:'SAST',label:'Fortify'},
																{name:'DAST',label:'OWASP ZAP'}]
						},
						{id:"5",name: 'Build and Release',eventKey:'buildrelease'},
						{id:"6",name: 'Insights',eventKey:'insights'}],
	}
},
{
	clientName: 'sloan',
	clientId: 'SLOAN',
	mappings: {
			showSprintDrop: false,
			navLogoUrl: 'overview',
			bgColor: 'light',
			logoName: 'EY Dash',
			projectLabel: 'Project',
			teamLabel: 'Teams',
			sprintLabel: 'Sprints',
			count: [{name:'Head Count'},{name:'Sprint Count'},{name: 'Team Head Count'}],
			feature: 'Features',
			userStory: 'User Stories',
			repository: 'Repository',
			branch: 'Branch',
			release: 'Release',
			roleDesignation: true,
			overviewBtn: 'Overview',
			buildBtn: 'Build',
			codeBtn: 'Code',
			alertBtn: 'Alerts',
			policiesBtn: 'Policies',
			critical: 'Critical',
			high: 'High',
			medium:'Medium',
			low: 'Low',
			veryLow: 'Very Low',
			major: 'Major',
			minor: 'Minor',
			tabItems: [{id:"1",name:'Overview',eventKey:'overview'},
						{id:"2",name: 'Velocity and Efficiency',eventKey:'velocity'},
						{id:"3",name: 'Quality',eventKey:'quality'},
						{id:"4",name: 'Build and Release',eventKey:'buildrelease'},
						{id:"5",name: 'Insights',eventKey:'insights'}],
	}
},
{
	clientName: 'blen',
	clientId: 'BLEN',
	mappings: {
			showSprintDrop: false,
			navLogoUrl: 'overview',
			bgColor: 'dark',
			logoName: 'BLEN Dashboard',
			projectLabel: 'Project',
			teamLabel: 'Project',
			sprintLabel: 'Sprints',
			count: [{name:'Head Count'},{name:'Sprint Count'},{name: 'Team Head Count'}],
			feature: 'Epics',
			userStory: 'User Stories',
			repository: 'Repository',
			branch: 'Branch',
			release: 'Release',
			roleDesignation: true,
			overviewBtn: 'Overview',
			buildBtn: 'Build',
			codeBtn: 'Code',
			alertBtn: 'Alerts',
			policiesBtn: 'Policies',
			critical: 'Critical',
			high: 'High',
			medium:'Medium',
			low: 'Low',
			veryLow: 'Very Low',
			major: 'Major',
			minor: 'Minor',
			tabItems: [{id:"1",name:'Overview',eventKey:'overview'},
						// {id:"2",name:'Security',eventKey:'security'},
						{id:"2",name: 'Velocity and Efficiency',eventKey:'velocity'},
						{id:"3",name: 'Quality',eventKey:'quality'},
						{id:"4",name: 'Build and Release',eventKey:'buildrelease'},
						{id:"5",name: 'Insights',eventKey:'insights'}],
	}
},
{
	clientName: 'aia',
	clientId: 'AIA',
	mappings: {
			showSprintDrop: true,
			navLogoUrl: 'overview',
			bgColor: 'light',
			logoName: 'AIA Dashboard',
			projectLabel: 'Projects',
			teamLabel: 'Teams',
			sprintLabel: 'Sprints',
			count: [{name:'Project Members'},{name:'Sprints'},{name: 'Team Members'}],
			feature: 'Features',
			userStory: 'User Stories',
			repository: 'Repository',
			branch: 'Branch',
			release: 'Release',
			roleDesignation: true,
			overviewBtn: 'Overview',
			buildBtn: 'Build',
			codeBtn: 'Code',
			alertBtn: 'Alerts',
			policiesBtn: 'Policies',
			critical: 'Critical',
			high: 'High',
			medium:'Medium',
			low: 'Low',
			veryLow: 'Very Low',
			major: 'Major',
			minor: 'Minor',
			tabItems: [{id:"1",name:'Overview',eventKey:'overview'},
						{id:"2",name: 'Velocity and Efficiency',eventKey:'velocity'},
						{id:"3",name: 'Quality',eventKey:'quality'},
						{id:"4",name:'Security',eventKey:'security',toolsDetails:
																				[{name:'SCA',label:'WhiteSource'},
																				{name:'SAST',label:'Fortify'},
																				{name:'DAST',label:'OWASP ZAP'}]
						},
						{id:"5",name: 'Build and Release',eventKey:'buildrelease'},
						{id:"6",name: 'Insights',eventKey:'insights'}]

	}
},
{
	clientName: 'wpc',
	clientId: 'WPC',
	mappings: {
			showSprintDrop: true,
			navLogoUrl: 'velocity',
			bgColor: 'dark',
			logoName: 'EY Dash',
			projectLabel: 'Portfolio',
			teamLabel: 'Projects',
			sprintLabel: 'Sprints',
			count: [],
			feature: 'Features',
			userStory: 'User Stories',
			qualityRepo: 'Show Code Quality',
			repository: 'Repository',
			branch: 'Branch',
			release: 'Release',
			roleDesignation: false,
			overviewBtn: 'Overview',
			buildBtn: 'Build',
			codeBtn: 'Code',
			alertBtn: 'Alerts',
			policiesBtn: 'Policies',
			critical: 'Critical',
			high: 'High',
			medium:'Medium',
			low: 'Low',
			veryLow: 'Very Low',
			major: 'Major',
			minor: 'Minor',
			tabItems: [{id:"1",name:'Overview',eventKey:'overview'},
						{id:"2",name: 'Velocity and Efficiency',eventKey:'velocity'},
						{id:"3",name: 'Quality',eventKey:'quality'},
						// {id:"3",name:'Security',eventKey:'security'},
						{id:"4",name: 'Build and Release',eventKey:'buildrelease'},
						{id:"5",name: 'Insights',eventKey:'insights'}]
	}
}];